ARM ID validation
Azure/oav pull request #851
Opened 2022-08-16 23:21 UTC by matthchr

2022-08-18 01:19 UTC, raych1 requested changes
Can you add some unit tests for arm-id validation at
https://github.com/Azure/oav/blob/develop/test/modelValidatorTests.ts

2022-08-18 22:14 UTC, matthchr commented
I've added a unit test @raych1. Let me know if you feel there should be more. I tried to follow the other format tests that I saw (`byte`).

2022-08-24 00:55 UTC, sanjaiganesh approved these changes

2022-09-20 08:13 UTC, raych1 approved these changes

2022-09-20 09:35 UTC, jianyexi commented on lib/swaggerValidator/modelValidator.ts
> +          exampleContent.responses[`${statusCode}`].body &&
```suggestion
          exampleContent.responses[statusCode].body &&
```

2022-09-20 09:36 UTC, jianyexi commented on lib/swaggerValidator/modelValidator.ts
> +          Object.keys(exampleContent.responses[`${statusCode}`].body).length === 0
```suggestion
          Object.keys(exampleContent.responses[statusCode].body).length === 0
```

2022-09-20 09:38 UTC, jianyexi approved these changes

2022-09-21 01:29 UTC, merged