loosen condition for duration check
Azure/oav pull request #883
Opened 2022-10-18 07:25 UTC by tadelesh

For some swagger [examples](https://github.com/Azure/azure-rest-api-specs/blob/ae227e20bcb22d83634452026f701d75bec2619e/specification/monitor/resource-manager/Microsoft.Insights/stable/2018-03-01/examples/createOrUpdateMetricAlertSingleResource.json#L17), durations are not case sensitive. Loosen validation regex could make them compatible. But if it should be tightly aligned with spec, just correct me.

2022-10-20 05:57 UTC, raych1 commented on lib/swaggerValidator/ajv.ts
> +      /^P([0-9]+(?:[,\.][0-9]+)?Y)?([0-9]+(?:[,\.][0-9]+)?M)?([0-9]+(?:[,\.][0-9]+)?D)?(?:T([0-9]+(?:[,\.][0-9]+)?H)?([0-9]+(?:[,\.][0-9]+)?M)?([0-9]+(?:[,\.][0-9]+)?S)?)?$/i,
The character format must be uppercase from durations definition at https://en.wikipedia.org/wiki/ISO_8601

2022-10-20 05:59 UTC, raych1 requested changes
@tadelesh,  it doesn't recognize the lowercase in durations format.

2022-10-20 12:54 UTC, tadelesh commented
> @tadelesh, it doesn't recognize the lowercase in durations format.

Some libraries loosen the condition to lowercase. But if you think it should be fixed with example, I'm OK with that. Besides, will lint rule check the example value of duration?

2022-11-02 03:47 UTC, raych1 commented
> > @tadelesh, it doesn't recognize the lowercase in durations format.
> 
> Some libraries loosen the condition to lowercase. But if you think it should be fixed with example, I'm OK with that. Besides, will lint rule check the example value of duration?

No, it just validates the format instead of the value correctness.

2022-11-02 03:47 UTC, closed without merging