[bugfix] playload uncorrect path
Azure/oav pull request #958
Opened 2023-02-06 08:07 UTC by JackTn

2023-02-06 08:08 UTC, JackTn commented
comment https://github.com/azure/oav/issues/947

2023-02-06 10:11 UTC, raych1 requested changes
Can you add changelog and bump patch version?

2023-02-09 11:26 UTC, leni-msft approved these changes

2023-02-10 03:02 UTC, raych1 approved these changes

2023-02-10 03:02 UTC, merged