support round trip validation
Azure/oav pull request #964
Opened 2023-02-14 13:26 UTC by xiaoxuqi-ms

2023-02-20 06:53 UTC, raych1 commented on lib/liveValidation/liveValidator.ts
>        const msg = "OperationLoader should be initialized before this call.";
Comment to update for function renaming.

2023-02-20 07:08 UTC, raych1 commented on lib/swagger/jsonFullResolvedLoader.ts
> +import { dirname as pathDirname } from "path";
What's the main diff of this file comparing to jsonLoader? It would be better to call the same code rather than having two copies.

2023-02-20 07:11 UTC, raych1 requested changes
Please hold off the merge until the change of `additionalProperties` validation RpaaS requested is delivered.

2023-02-21 10:35 UTC, raych1 commented on test/liveValidatorTests.ts
> +        enableRoundTripValidator: true
why do you enable roundtrip for live validator tests? It's ok to have a new single test to validate roundtrip validation enablement doesn't impact live validation.

2023-02-21 10:37 UTC, raych1 commented on lib/liveValidation/liveValidator.ts
>        const msg = "OperationLoader should be initialized before this call.";
Can you update msg in line#754?

2023-02-23 03:02 UTC, leni-msft requested changes

2023-02-23 03:02 UTC, leniatgh commented on lib/armValidator/roundTripValidator.ts
> +            isAllowed || checkReplacedSchemaInParameter(it.replace, parameter, jsonLoader);
we can use `|=`

2023-02-23 03:02 UTC, leniatgh commented on lib/armValidator/roundTripValidator.ts
> +        for (let parameter of info.operationMatch?.operation._path.parameters ?? []) {
If isAllowed is true, we don't need check other parameters.

2023-02-23 03:02 UTC, leniatgh commented on lib/armValidator/roundTripValidator.ts
> +        isSubset(foundSchema["x-ms-mutability"], ["create", "update"]))
`x-ms-mutability` is array of string, so maybe we could use `Array.prototype.every` to check, for better readability.

2023-02-23 03:02 UTC, leniatgh commented on lib/armValidator/roundTripValidator.ts
> +    statusCode = statusCodeMap.get(responseStatusCode.toUpperCase());
you can use `statusCodeStringToStatusCode` in utils.ts

2023-02-23 03:02 UTC, leniatgh commented on lib/armValidator/roundTripValidator.ts
> +const notAllowed = false;
seems unnecessary constants

2023-02-23 03:02 UTC, leni-msft commented on lib/liveValidation/liveValidator.ts
> +    this.withRefSibingsOperationSearcher = new OperationSearcher(this.logging);
why do we duplicate operationSearcher instance?

2023-02-23 09:06 UTC, leni-msft approved these changes

2023-02-24 02:28 UTC, raych1 commented on lib/liveValidation/liveValidator.ts
> +      const msg = "withRefSibingsOperationSearcher should be initialized before this call.";
```suggestion
      const msg = "operationSearcher should be initialized before this call.";
```

2023-02-24 02:29 UTC, raych1 commented on ChangeLog.md
> +- Fix roundtrip validation model with circular reference
New version should be 3.2.7.

2023-02-24 04:04 UTC, raych1 commented on ChangeLog.md
> +## 02/04/2023 3.2.7
```suggestion
## 02/24/2023 3.2.7
```

2023-02-24 04:05 UTC, raych1 approved these changes

2023-02-25 02:37 UTC, xiaoxuqi-ms commented
/azp run

2023-02-25 02:37 UTC, merged